### ISSUE TITLE
Error thrown during saving the auth data: Error: File APL was unable to save auth data

### ISSUE THREAD

**Issue by gempain** [saleor/react-storefront#753]
### Summary

I followed the deployment guide [here](https://github.com/saleor/react-storefront/blob/canary/docs/vercel.md).

When I install the checkout app from the Saleor dashboard, it is correctly added, but the setup fails and I see this error in Vercel:

```
[POST] /api/register/
18:01:41:95
Error thrown during saving the auth data: Error: File APL was unable to save auth data
    at FileAPL.saveDataToFile (file:///var/task/node_modules/.pnpm/registry.npmjs.org+@saleor+app-sdk@0.23.0_dcors23iqtgxrhrwosgnnc4xji/node_modules/@saleor/app-sdk/APL/index.mjs:45:13)
    at async FileAPL.set (file:///var/task/node_modules/.pnpm/registry.npmjs.org+@saleor+app-sdk@0.23.0_dcors23iqtgxrhrwosgnnc4xji/node_modules/@saleor/app-sdk/APL/index.mjs:56:5)
    at async unpackPromise (/var/task/apps/saleor-app-checkout/.next/server/chunks/5474.js:224:24)
    at async handler (/var/task/apps/saleor-app-checkout/.next/server/pages/api/register.js:67:21)
    at async Object.apiResolver (/var/task/node_modules/.pnpm/registry.npmjs.org+next@13.0.4_672uxklweod7ene3nqtsh262ca/node_modules/next/dist/server/api-utils/node.js:367:9)
    at async NextNodeServer.runApi (/var/task/node_modules/.pnpm/registry.npmjs.org+next@13.0.4_672uxklweod7ene3nqtsh262ca/node_modules/next/dist/server/next-server.js:474:9)
    at async Object.fn (/var/task/node_modules/.pnpm/registry.npmjs.org+next@13.0.4_672uxklweod7ene3nqtsh262ca/node_modules/next/dist/server/next-server.js:736:37)
    at async Router.execute (/var/task/node_modules/.pnpm/registry.npmjs.org+next@13.0.4_672uxklweod7ene3nqtsh262ca/node_modules/next/dist/server/router.js:252:36)
    at async NextNodeServer.run (/var/task/node_modules/.pnpm/registry.npmjs.org+next@13.0.4_672uxklweod7ene3nqtsh262ca/node_modules/next/dist/server/base-server.js:384:29)
    at async NextNodeServer.handleRequest (/var/task/node_modules/.pnpm/registry.npmjs.org+next@13.0.4_672uxklweod7ene3nqtsh262ca/node_modules/next/dist/server/base-server.js:322:20)
```

However, I deployed slightly differently the app, it's built in Github Actions and deployed using vercel CLI.

```
name: 'checkout app'

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *' # Every day midnight

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: 'Build'
        run: |
          TARBALL_URL=https://github.com/saleor/react-storefront/tarball/main
          wget -c "$TARBALL_URL" -O - | tar -xz
          
          cd saleor-react-storefront-*
          
          # build
          npm install -g vercel@latest
          vercel pull --yes --environment=production --token=${{ secrets.APP_CHECKOUT_VERCEL_TOKEN }}
          vercel build --prod --token=${{ secrets.APP_CHECKOUT_VERCEL_TOKEN }}
          vercel deploy --prod --prebuilt --token=${{ secrets.APP_CHECKOUT_VERCEL_TOKEN }}
        env:
          HUSKY: 0 # disable husky, otherwise pnpm install fails
          VERCEL_ORG_ID: ${{ secrets.APP_CHECKOUT_VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.APP_CHECKOUT_VERCEL_PROJECT_ID }}
          # app env variables
          ENABLE_EXPERIMENTAL_COREPACK: 1
          SETTINGS_ENCRYPTION_SECRET: ${{ secrets.APP_CHECKOUT_SETTINGS_ENCRYPTION_SECRET }}
          NEXT_PUBLIC_SALEOR_API_URL: https://mydomain.com/graphql/
          SALEOR_APP_TOKEN: ${{ secrets.APP_CHECKOUT_SALEOR_APP_TOKEN }}
          APL: 'vercel'
          CHECKOUT_APP_URL: https://checkout.mydomain.com
```

### Steps to reproduce

1. create a new project in Vercel as described by [the docs](https://github.com/saleor/react-storefront/blob/canary/docs/vercel.md)
2. build locally and deploy to vercel using their CLI
3. Install the app in Saleor
